spring:
  application:
    name: parking-management-service

  main:
    web-application-type: servlet
    banner-mode: off

  docker:
    compose:
      enabled: false

  jpa:
    open-in-view: false

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true